# Run the 'nginx-rootless' container as an arbitrary UID & GID.
# Be sure that the image name matches your httpd image name,
# and replace YourUserID:YourGroupID with your own UserID & GroupID.
version: '2'
services:
  web:
    image: nginx-rootless:v1
    ports:
    - 80:8080
    user: YourUserID:YourGroupID
    # Also add www-data as a supplementary group
    group_add:
    - nginx
    cap_drop:
    - ALL
