# Run the 'httpd-rootless' container as an arbirary UID & GID.
# Be sure that the image name matches your httpd image name,
# and replace YourUserID:YourGroupID with your own UserID & GroupID.
# Note: This image will not work if you use a username:group,
# because the username & group do not exist in the image.
version: '2'
services:
  web:
    image: httpd-rootless
    ports:
    - 80:8080
    user: YourUserID:YourGroupID
    # Also add www-data as a supplementary group
    group_add:
    - www-data
    cap_drop:
    - ALL
