#
# to use this template, substitute the following throughout:
#
# - for postgres-root: your stack name
# - for PostgresUser: your Postgres user name
# - for ProjectDir: your global file system project directory
# - for UserID: your numeric user ID that should own the dump files
# - for GroupID: your numeric group ID that should own the dump files

version: '2'

services:
    db:
        image: postgres:10-alpine

        # uncomment only if access outside of Spin is needed
        #ports:
        #    - 5432:5432/tcp

        stdin_open: true
        tty: true

        volumes:
            - db.postgres-root:/var/lib/postgresql/data

        # substitute the account name to be used to access the database below
        environment:
            POSTGRES_USER: PostgresUser
            POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password

        cap_drop:
            - ALL
        cap_add:
            - CHOWN
            - DAC_OVERRIDE
            - FOWNER
            - SETGID
            - SETUID

        secrets:
            - mode: '0444'
              uid: '0'
              gid: '0'
              source: db.postgres-root.postgres_password
              target: postgres_password

        # uncomment to set configuration options as needed
        # (this is cleaner than creating your own image with a custom config file)
        #command:
        #    - postgres
        #    - -c
        #    - max_connections=100
        #    - -c
        #    - shared_buffers=32MB

        labels:

            # prevent running stale (cached) image on restart or upgrade
            io.rancher.container.pull_image: always

    db-dump:
        image: registry.spin.nersc.gov/pub/postgres-pg_dump:10-alpine

        stdin_open: true
        tty: true

        volumes:
        - /global/project/projectdirs/ProjectDir/path/to/dump/:/pg_dump

        # further customize filenames and retention (-1 for indefinite) below as needed
        environment:
            POSTGRES_HOST: db
            POSTGRES_USER: PostgresUser
            POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
            POSTGRES_DUMP_DIR: /pg_dump
            POSTGRES_DUMP_FILE_BASE: db-dump.sql.gz
            POSTGRES_DUMP_RETAIN_DAYS: '7'
            TZ: US/Pacific

        cap_drop:
            - ALL

        secrets:
            - mode: '0400'
              uid: 'UserID'
              gid: 'GroupID'
              source: db.postgres-root.postgres_password
              target: postgres_password

        user: UserID:GroupID

        labels:

            # prevent running stale (cached) image on restart or upgrade
            io.rancher.container.pull_image: always

            # run at 11am (UTC)
            cron.schedule: 0 0 11 * * *

            # override default behavior to restart container after backup process completes
            io.rancher.container.start_once: 'true'

#
# note: secrets and volumes must have been created manually
#

secrets:
    db.postgres-root.postgres_password:
        external: true

volumes:
    db.postgres-root:
        driver: rancher-nfs
        external: true
